# Fem structural analysis code for finding displacement in homogeneous 2d bar elements.

In [3]:
import numpy as np
n=4 #number of elements
elements=[]
for i in range(1,n+1):
    elements.append(i)
    
    
print((elements))
#properties of elements in a member
theta=[0,45,0,90]    #angle in degrees with respect to horizontal
E=[280000000000,280000000000,280000000000,280000000000]  #Modulus of Elasticity
L=[1.5,2.12,1.5,1.5]      #Length of Each Element
A=[0.000314,0.000314,0.000314,0.000314] #Area of each element
stifness=elements
for i in range(0,n):
    stifness[i]=A[i-1]*E[i-1]/L[i]
    print(stifness[i])
#print(stifness[1])
   

[1, 2, 3, 4]
58613333.333333336
41471698.11320754
58613333.333333336
58613333.333333336


In [4]:
elementinfo=[]
for i in range(1,n+1):
    elementinfo.append(i)
for i in range(0,n):      #node element information
    print('enter the no of nodes releated to element:')
    x=int(input())
    y=int(input())
    elementinfo[i]=np.array([x,y])
print(elementinfo)



enter the no of nodes releated to element:
1
4
enter the no of nodes releated to element:
1
3
enter the no of nodes releated to element:
2
3
enter the no of nodes releated to element:
3
4
[array([1, 4]), array([1, 3]), array([2, 3]), array([3, 4])]


In [5]:
#element matrix
R=elements 
for i in range (0,n):
    c=np.cos(theta[i]*np.pi/180)
    s=np.sin(theta[i]*np.pi/180)
    R[i]=np.array([[c*c,c*s,-c*c,-c*s],[c*s,s*s,-c*s,-s*s],[-c*c,-c*s,c*c,c*s],[-c*s,-s*s,c*s,s*s]])*stifness[i]
    print('stifness matrix for element',i+1)
    print(R[i])   

stifness matrix for element 1
[[ 58613333.33333334         0.         -58613333.33333334
         -0.        ]
 [        0.                 0.                -0.
         -0.        ]
 [-58613333.33333334        -0.          58613333.33333334
          0.        ]
 [       -0.                -0.                 0.
          0.        ]]
stifness matrix for element 2
[[ 20735849.05660377  20735849.05660377 -20735849.05660377
  -20735849.05660377]
 [ 20735849.05660377  20735849.05660377 -20735849.05660377
  -20735849.05660377]
 [-20735849.05660377 -20735849.05660377  20735849.05660377
   20735849.05660377]
 [-20735849.05660377 -20735849.05660377  20735849.05660377
   20735849.05660377]]
stifness matrix for element 3
[[ 58613333.33333334         0.         -58613333.33333334
         -0.        ]
 [        0.                 0.                -0.
         -0.        ]
 [-58613333.33333334        -0.          58613333.33333334
          0.        ]
 [       -0.                -0.          

In [6]:
elementinfo[1]
nodes=int(input('enter the number of nodes'))


enter the number of nodes4


In [7]:
#global matrix
kglobal=np.zeros((2*nodes,2*nodes))
for i in range (0,n):
    
    #print(2*elementinfo[i][0]-2,2*elementinfo[i][0]-2,'  ',R[i][0][0])
    kglobal[2*elementinfo[i][0]-2,2*elementinfo[i][0]-2]=kglobal[2*elementinfo[i][0]-2,2*elementinfo[i][0]-2]+R[i][0][0]
    
    
    #print(2*elementinfo[i][0]-2,2*elementinfo[i][0]-1,'  ',R[i][0][1])
    kglobal[2*elementinfo[i][0]-2,2*elementinfo[i][0]-1]=kglobal[2*elementinfo[i][0]-2,2*elementinfo[i][0]-1]+R[i][0][1]
    
    
    #print(2*elementinfo[i][0]-2,2*elementinfo[i][1]-2,'  ',R[i][0][2])
    kglobal[2*elementinfo[i][0]-2,2*elementinfo[i][1]-2]=kglobal[2*elementinfo[i][0]-2,2*elementinfo[i][1]-2]+R[i][0][2]
    
    
    #print(2*elementinfo[i][0]-2,2*elementinfo[i][1]-1,'  ',R[i][0][3])
    kglobal[2*elementinfo[i][0]-2,2*elementinfo[i][1]-1]=kglobal[2*elementinfo[i][0]-2,2*elementinfo[i][1]-1]+R[i][0][3]
    
    
    #print(2*elementinfo[i][0]-1,2*elementinfo[i][0]-2,'  ',R[i][1][0])
    kglobal[2*elementinfo[i][0]-1,2*elementinfo[i][0]-2]=kglobal[2*elementinfo[i][0]-1,2*elementinfo[i][0]-2]+R[i][1][0]
    
    
    #print(2*elementinfo[i][0]-1,2*elementinfo[i][0]-1,'  ',R[i][1][1])
    kglobal[2*elementinfo[i][0]-1,2*elementinfo[i][0]-1]=kglobal[2*elementinfo[i][0]-1,2*elementinfo[i][0]-1]+R[i][1][1]
    
    
    #print(2*elementinfo[i][0]-1,2*elementinfo[i][1]-2,'  ',R[i][1][2])
    kglobal[2*elementinfo[i][0]-1,2*elementinfo[i][1]-2]=kglobal[2*elementinfo[i][0]-1,2*elementinfo[i][1]-2]+R[i][1][2]
    
    
    
    #print(2*elementinfo[i][0]-1,2*elementinfo[i][1]-1,'  ',R[i][1][3])
    kglobal[2*elementinfo[i][0]-1,2*elementinfo[i][1]-1]=kglobal[2*elementinfo[i][0]-1,2*elementinfo[i][1]-1]+R[i][1][3]
    
    
    #print(2*elementinfo[i][1]-2,2*elementinfo[i][0]-2,'  ',R[i][2][0])
    kglobal[2*elementinfo[i][1]-2,2*elementinfo[i][0]-2]=kglobal[2*elementinfo[i][1]-2,2*elementinfo[i][0]-2]+R[i][2][0]
    
    
    #print(2*elementinfo[i][1]-2,2*elementinfo[i][0]-1,'  ',R[i][2][1])
    kglobal[2*elementinfo[i][1]-2,2*elementinfo[i][0]-1]=kglobal[2*elementinfo[i][1]-2,2*elementinfo[i][0]-1]+R[i][2][1]
    
    
    #print(2*elementinfo[i][1]-2,2*elementinfo[i][1]-2,'  ',R[i][2][2])
    kglobal[2*elementinfo[i][1]-2,2*elementinfo[i][1]-2]=kglobal[2*elementinfo[i][1]-2,2*elementinfo[i][1]-2]+R[i][2][2]
    
    
    #print(2*elementinfo[i][1]-2,2*elementinfo[i][1]-1,'  ',R[i][2][3])
    kglobal[2*elementinfo[i][1]-2,2*elementinfo[i][1]-1]=kglobal[2*elementinfo[i][1]-2,2*elementinfo[i][1]-1]+R[i][2][3]
    
    
    #print(2*elementinfo[i][1]-1,2*elementinfo[i][0]-2,'  ',R[i][3][0])
    kglobal[2*elementinfo[i][1]-1,2*elementinfo[i][0]-2]=kglobal[2*elementinfo[i][1]-1,2*elementinfo[i][0]-2]+R[i][3][0]
    
    
    #print(2*elementinfo[i][1]-1,2*elementinfo[i][0]-1,'  ',R[i][3][1])
    kglobal[2*elementinfo[i][1]-1,2*elementinfo[i][0]-1]=kglobal[2*elementinfo[i][1]-1,2*elementinfo[i][0]-1]+R[i][3][1]
    
    
    #print(2*elementinfo[i][1]-1,2*elementinfo[i][1]-2,'  ',R[i][3][2])
    kglobal[2*elementinfo[i][1]-1,2*elementinfo[i][1]-2]=kglobal[2*elementinfo[i][1]-1,2*elementinfo[i][1]-2]+R[i][3][2]
    
    
    #print(2*elementinfo[i][1]-1,2*elementinfo[i][1]-1,'  ',R[i][3][3])
    kglobal[2*elementinfo[i][1]-1,2*elementinfo[i][1]-1]=kglobal[2*elementinfo[i][1]-1,2*elementinfo[i][1]-1]+R[i][3][3]
    

                        
                     
                        
print(kglobal)                   


[[ 7.93491824e+07  2.07358491e+07  0.00000000e+00  0.00000000e+00
  -2.07358491e+07 -2.07358491e+07 -5.86133333e+07  0.00000000e+00]
 [ 2.07358491e+07  2.07358491e+07  0.00000000e+00  0.00000000e+00
  -2.07358491e+07 -2.07358491e+07  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  5.86133333e+07  0.00000000e+00
  -5.86133333e+07  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.07358491e+07 -2.07358491e+07 -5.86133333e+07  0.00000000e+00
   7.93491824e+07  2.07358491e+07 -2.19764800e-25 -3.58903155e-09]
 [-2.07358491e+07 -2.07358491e+07  0.00000000e+00  0.00000000e+00
   2.07358491e+07  7.93491824e+07 -3.58903155e-09 -5.86133333e+07]
 [-5.86133333e+07  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -2.19764800e-25 -3.58903155e-09  5.86133333e+07  3.58903155e-09]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -

In [9]:
# applied forces
F=np.array([[5000],[7000],[0],[0]])
print(F)




[[5000]
 [7000]
 [   0]
 [   0]]


In [10]:
# chopout constraint rows and coloumns.
mat=(np.delete(kglobal,[0,1,2,3],0))
matrix=np.delete(mat,[0,1,2,3],1)



In [11]:

print(matrix)

[[ 7.93491824e+07  2.07358491e+07 -2.19764800e-25 -3.58903155e-09]
 [ 2.07358491e+07  7.93491824e+07 -3.58903155e-09 -5.86133333e+07]
 [-2.19764800e-25 -3.58903155e-09  5.86133333e+07  3.58903155e-09]
 [-3.58903155e-09 -5.86133333e+07  3.58903155e-09  5.86133333e+07]]


In [12]:
matrixinv=np.linalg.inv(matrix)
print(matrixinv)

[[ 1.70609645e-08 -1.70609645e-08  3.36635428e-42 -1.70609645e-08]
 [-1.70609645e-08  6.52866242e-08 -1.28819157e-41  6.52866242e-08]
 [-8.42983752e-42  1.75127929e-40  1.70609645e-08 -1.04468278e-24]
 [-1.70609645e-08  6.52866242e-08 -1.04468278e-24  8.23475887e-08]]


In [13]:
# matrixmultiplication
displacements=np.matmul(matrixinv,F)
print(displacements)

[[-3.41219290e-05]
 [ 3.71701547e-04]
 [ 1.18374632e-36]
 [ 3.71701547e-04]]


In [14]:
# displacement vector is given by.

displace=np.array([[0],[0],[0],[0],[0.0005333],[0.001729]])

In [92]:
# forces 
forces=np.matmul(kglobal,displace)
print(forces)

[[-299.98673975]
 [-299.98673975]
 [-199.9875    ]
 [   0.        ]
 [ 499.97423975]
 [ 299.98673975]]
